### ISSUE TITLE
how can i use multiple where condition in a array in one where method as eloquent usage

### ISSUE THREAD

**Issue by fizzday** [sdispater/orator#103]
the eloquent usage like:
```
User::where(array(array('id', '>', 3), array('name', 'like', '%fizz%')))->get();
```
I tried the orator usage like:
```
User.where([ ['id', '>', '1'] ]).get()
````
I get the error:
```
orator.exceptions.ArgumentError: Value must be provided
```
is orator support this usage like???

**Comment by Agnewee** [comment]
Of course.
```python
User.where('id', '>', 1).get()
```
You should read [official doc](https://orator-orm.com/docs/0.9/orm.html#retrieving-a-model-by-primary-key-or-raise-an-exception)

**Comment by sdispater** [comment]
@fizzday Passing multiple conditions as a list in the `where()` method is not currently supported.

**Comment by sdispater** [comment]
@fizzday It's now possible to do that in the latest `0.9.2` release.
