### ISSUE TITLE
How to Migrate db in the script ?

### ISSUE THREAD

**Issue by Agnewee** [sdispater/orator#105]
Now I want to run the migration in a script file. 

I try to run it like command line
```python
import commands
...
result = commands.getoutput('echo y|orator migrate -c db.py')
...
```
```python
databases = {
    'sqlite': {
        'driver': 'sqlite',
        'database': 'test.sqlite'     # any flexible way to pass db file?
    }
}

db = DatabaseManager(databases)
schema = Schema(db)
```
but sometimes the run path not in `test.sqlite` dir.

i means that the model file also need import the `db`, but if  `from ..db import db` will throw exception.

how can i make it flexibly in the script file ?

**Comment by sdispater** [comment]
It's not trivial to migrate programmatically, however you can take the code of the `migrate` command as a starting point:

```python
from orator.migrations import Migrator, DatabaseMigrationRepository

databases = {
    'sqlite': {
        'driver': 'sqlite',
        'database': 'test.sqlite'
    }
}

db = DatabaseManager(databases)

repository = DatabaseMigrationRepository(db, 'migrations')
migrator = Migrator(repository, db)

migrator.set_connection('sqlite')

if not migrator.repository_exists():
    repository.create_repository()

migrator.run(path, False)
# path here should be the path to the migrations directory

for note in migrator.get_notes():
    print(note)
```

However, be aware this is part of the internal logic of Orator and is not considered to be part of the public API so it might break in future version.

**Comment by Agnewee** [comment]
I got it. thanks so mush
