### ISSUE TITLE
Weird behaviour when working with not-incremental IDs

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator#106]
This issue happens when I have to set IDs manually, and I don't want to use them in the regular way with auto-incrementing trigger.

Model:
```python
class BudgetCategory(Model):
    __autoincrementing__ = False
    __fillable__ = ['id', 'name']
```

Script with results:
```python
custom_id = 33
category_name = 'Sample'

category = BudgetCategory(id=custom_id, name=category_name)
print(category.serialize())
# {'id': 33, 'name': 'Sample'}

category.save()
print(category.serialize())
# {'id': 6, 'updated_at': '2016-09-27T14:00:06.758576+00:00', 'created_at': '2016-09-27T14:00:06.758576+00:00', 'name': 'Sample'}

temp_category = BudgetCategory.find(custom_id)
print(temp_category.serialize())
# {'id': 33, 'updated_at': '2016-09-27T14:00:06.758576+00:00', 'created_at': '2016-09-27T14:00:06.758576+00:00', 'name': 'Sample'}
```

After saving, the 'id' property seems to follow the incrementing order, but only in the model object. In the database, the record is saved correctly.

btw: I'm using SQLite.

Thanks!

**Comment by sdispater** [comment]
It seems that the `__autoincrementing_ = False` is not honored and `insert_get_id()` is called regardless.

I will look into it.

**Comment by sdispater** [comment]
Oh! It's not `__autoincrementing__` but `__incrementing__` that's why it behaves like it does.

**Comment by sdispater** [comment]
I just fixed the documentation.
