### ISSUE TITLE
Running migrate gives TypeError

### ISSUE THREAD

**Issue by totalpeople** [sdispater/orator#107]
Hi, I'm getting this error when I'm running the migrate command. Any ideas how I can get it to work?

`[TypeError]
  unsupported operand type(s) for +: 'NoneType' and 'str'

Exception trace:
 /usr/local/lib/python3.5/dist-packages/cleo/application.py in run() at line 96
   status_code = self.do_run(input_, output_)
 /usr/local/lib/python3.5/dist-packages/cleo/application.py in do_run() at line 188
   status_code = command.run(input_, output_)
 /usr/local/lib/python3.5/dist-packages/cleo/commands/command.py in run() at line 90
   return super(Command, self).run(i, o)
 /usr/local/lib/python3.5/dist-packages/cleo/commands/base_command.py in run() at line 144
   status_code = self.execute(input_, output_)
 /usr/local/lib/python3.5/dist-packages/orator/commands/command.py in execute() at line 39
   return self.handle()
 /usr/local/lib/python3.5/dist-packages/orator/commands/migrations/migrate_command.py in handle() at line 33
   self._prepare_database(migrator, database)
 /usr/local/lib/python3.5/dist-packages/orator/commands/migrations/migrate_command.py in _prepare_database() at line 68
   if not migrator.repository_exists():
 /usr/local/lib/python3.5/dist-packages/orator/migrations/migrator.py in repository_exists() at line 298
   return self._repository.repository_exists()
 /usr/local/lib/python3.5/dist-packages/orator/migrations/database_migration_repository.py in repository_exists() at line 94
   return schema.has_table(self._table)
 /usr/local/lib/python3.5/dist-packages/orator/schema/mysql_builder.py in has_table() at line 19
   table = self._connection.get_table_prefix() + table`

**Comment by sdispater** [comment]
What is your backend (`sqlite`, `mysql` or `postgresql`) ? And what package are you using to connect to it (`sqlite3`, `mysqlclient`, `pymysql` or `psycopg2`) ?

**Comment by totalpeople** [comment]
Hi I'm using mysql and installed pymysql

**Comment by sdispater** [comment]
What is you configuration for you database (replace sensitive  information) ? Have you set a `prefix` configuration ?

**Comment by totalpeople** [comment]
I moved my settings to a config.yml file and set prefix to nothing. I then changed my db.py file to an empty string and it's worked.

I changed this ...

`
databases = {
    'mysql': {
        'driver': config['databases']['mysql']['driver'],
        'host': config['databases']['mysql']['host'],
        'database': config['databases']['mysql']['database'],
        'user': config['databases']['mysql']['user'],
        'password': config['databases']['mysql']['password'],
        'prefix': config['databases']['mysql']['prefix']
    }
}
`

To this...

`
databases = {
    'mysql': {
        'driver': config['databases']['mysql']['driver'],
        'host': config['databases']['mysql']['host'],
        'database': config['databases']['mysql']['database'],
        'user': config['databases']['mysql']['user'],
        'password': config['databases']['mysql']['password'],
        'prefix': ''
    }
}
`

Thanks for giving me the hint!

**Comment by sdispater** [comment]
I will improve this to automatically set the `prefix` to `''` if it is set to `None` in the config.
