### ISSUE TITLE
Incorrect datetime value: '2016-10-13 18:59:57.892599+00:00' for column 'created_at' at row 1")

### ISSUE THREAD

**Issue by 12789** [sdispater/orator#109]
Orator-ORM: 0.9.1
Python: 2.7.10
MySQL: 5.7.15

It happened when I save a model.

`orator.exceptions.query.QueryException: (1292, "Incorrect datetime value: '2016-10-13 18:59:57.892599+00:00' for column 'created_at' at row 1") (SQL: INSERT INTO `admins` (`created_at`, `email`, `updated_at`) VALUES (%s, %s, %s) ([<Pendulum [2016-10-13T18:59:57.892599+00:00]>, 'abc@gmail.com', <Pendulum [2016-10-13T18:59:57.892599+00:00]>]))`

The migration script:

```
from orator.migrations import Migration


class CreateAdminsTable(Migration):

    def up(self):
        """
        Run the migrations.
        """
        with self.schema.create('admins') as table:
            table.increments('id')
            table.string('email', 64).unique()
            table.json('profile').nullable()
            table.json('token').nullable()
            table.small_integer('status').default(0)
            table.timestamps()

    def down(self):
        """
        Revert the migrations.
        """
        self.schema.drop('admins')

```

I guess the question is timezone info (+00:00).

**Comment by sdispater** [comment]
Are you using `mysqlclient` or `PyMySQL` as your database package?

**Comment by 12789** [comment]
@sdispater Yes, I have installed PyMySQL package.

**Comment by sdispater** [comment]
Which version of PyMySQL do you use?

**Comment by 12789** [comment]
@sdispater PyMySQL (0.7.9)

**Comment by sdispater** [comment]
Thanks. I will check out what the problem is an get back to you.

**Comment by sdispater** [comment]
I can't reproduce. How do you save your model?

**Comment by 12789** [comment]
@sdispater 

```
class Admin(db.Model):

    def __repr__(self):
        return '<Admin %r>' % self.id
```
```
admin = Admin()
admin.email = email
admin.save()
```

**Comment by sdispater** [comment]
That's strange. I still can't reproduce. Everything is behaving as expected on my end.

Here is the query that is executed on my system:

```sql
INSERT INTO `admins` (`created_at`, `email`, `updated_at`)
 VALUES ('2016-10-14 17:10:25.721616', 'test@example.com', '2016-10-14 17:10:25.721616')
```

Pendulum instances are properly formatted in my case.

**Comment by 12789** [comment]
@sdispater 
I made a new env by virtualenv for test, The model works perfect.
I try to find out what happened. 
After all, it reproduced when I installed MySQL-python.

**Comment by sdispater** [comment]
I can only reproduce with the `mysql-python` package which is not supported by `orator` you should use `mysqlclient` which is an up-to-date version of `mysql-python` which also support python 3. Or you can use `pymysql`.

Also if you have both installed, `mysqlclient` (or `mysql-python`) will have priority.

**Comment by 12789** [comment]
Got it.

I've installed MySQL-python and PyMySQL, so I have to uninstall MySQL-python to fix the issue, right?

**Comment by sdispater** [comment]
Yes.

And if you ever need `mysql-python`, use `mysqlclient` instead.
