### ISSUE TITLE
Question: is there any way to run a complete raw query?

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator#118]
Hi @sdispater,

I was wondering if it would be possible to run a complete raw query at once, without the need of spliting it. Let me explain: I'm currently working on a project which has some _really big_ queries. Right now, I'm using lots of ```db.raw('...')``` inside ```db.select()``` or ```.where_raw('...')``` and so on.

I think it would be nice to have a method (if we doesn't have one already, I couldn't find it in the docs) to call a whole query at once, like this:

```python
long_query = 'SELECT ...'

db = DatabaseManager(config)
res = db.raw_query(long_query).run()  # or somehting similar
```

What do you think about it?
Thanks for the support!

**Comment by sdispater** [comment]
@joaobarbosa You can just pass your raw query to `db.select()`:

```python
users = db.select("SELECT * FROM users WHERE name LIKE '%john%'")
```

**Comment by joaobarbosa** [comment]
Nice! :)
Thanks a lot!
