### ISSUE TITLE
View ORM query

### ISSUE THREAD

**Issue by patrickcteng** [sdispater/orator#124]
This may be a naive question, but is there a way to view the raw query that's issued to the DB when I'm using the ORM models? I know I can write the SQL query to match what the ORM is doing, but I just want to be able to make sure it's querying as I'm expecting it to query. 

Thanks.

**Comment by sdispater** [comment]
You can use the `to_sql()` method.

```python
>>> query = Users.where('name', '=', 'John').and_where('age', '>', 30)
>>> query.to_sql()
'SELECT * FROM "users" WHERE "name" = ? AND "age" > ?'
```

If you want to get the list of the bindings, use the `get_bindings()` method.

```python
>>> query.get_bindings()
['John', 30]
```

**Comment by patrickcteng** [comment]
Thank you!
