### ISSUE TITLE
ImportError: The ``fake-factory`` package is now called ``Faker``

### ISSUE THREAD

**Issue by acristoffers** [sdispater/orator#126]
An update to fake-factory changed the package name. The relevant part of the exception is:

File "/usr/local/lib/python3.5/site-packages/orator/orm/factory.py", line 5, in <module>
    from faker import Faker
  File "/usr/local/lib/python3.5/site-packages/faker/__init__.py", line 7, in <module>
    raise ImportError(error)
ImportError: The ``fake-factory`` package is now called ``Faker``.

**Comment by acristoffers** [comment]
It's not just a rename, the fake-factory package is now deprecated and the package Faker should be used. See https://pypi.python.org/pypi/fake-factory

**Comment by byronformwalt** [comment]
Here is what worked for me:
`$ pip uninstall fake-factory`
`$ pip install Faker`
On my first attempt, I used `$ pip install faker`, which did not work.  Apparently, package names are case sensitive.

**Comment by acristoffers** [comment]
I made a pull request ( #128 ) that changes the requirement. With that I can run my application again. I don't know, however, how much the API changed, if at all.

**Comment by sdispater** [comment]
I just merged your PR.

I don't think the API has changed that much from what I've seen so we should be good.

**Comment by istommao** [comment]
I Encounter this problem too, When to release hotfix?

**Comment by tcwalther** [comment]
Would it be possible to release a minor update with the updated dependency?

**Comment by sdispater** [comment]
I will release the bugfix version in the coming week.

**Comment by sdispater** [comment]
Version `0.9.4` has just been released.
