### ISSUE TITLE
make:migrate doesn't show the name of the created file

### ISSUE THREAD

**Issue by denislins** [sdispater/orator#138]
This would be a very handy addition as it would enable us to copy the file name and open it directly in Sublime, Atom or whatever. ActiveRecord, Eloquent and other libraries already do this.

Today I have to manually navigate to the migrations folder and look the newest file there. This can become even more annoying when the number of migrations start to grow.

Would this be a good addition? I'd be willing to write the PR.

**Comment by sdispater** [comment]
Yes, I agree that would be useful.

Feel free to make a PR :-)

**Comment by denislins** [comment]
Awesome. I'll attend a conference this weekend, but the PR should be ready by Monday.
