### ISSUE TITLE
MySQL autocommit

### ISSUE THREAD

**Issue by crowdmetricivar** [sdispater/orator#143]
Im getting the error below while testing out orator with mysql

 File "/usr/local/lib/python2.7/dist-packages/orator/connectors/mysql_connector.py", line 95, in _do_connect
    return self.get_api().connect(**self.get_config(config))

**TypeError: 'autocommit' is an invalid keyword argument for this function**

i have PyMSQL and mysqldb installed. 
i get the error while running select command on the DataManager instance

**Comment by crowdmetricivar** [comment]
i got it working by editing mysql_connector.py

the issue here is that on mysqldb, setting auto_commit is not supposed to be via config

here are my changes

**is_mysqldb = False**
try:
    import MySQLdb as mysql

    # Fix for understanding Pendulum object
    import MySQLdb.converters
    MySQLdb.converters.conversions[Pendulum] = MySQLdb.converters.DateTime2literal

    from MySQLdb.cursors import DictCursor as cursor_class
    keys_fix = {
        'password': 'passwd',
        'database': 'db'
    }
    **is_mysqldb = True**
except ImportError as e:
...

and then on 

def _do_connect(self, config):
        config = dict(config.items())
        for key, value in keys_fix.items():
            config[value] = config[key]
            del config[key]

        **#config['autocommit'] = True**
        config['cursorclass'] = self.get_cursor_class(config)

        **the_connection = None
        if not is_mysqldb:
           config['autocommit'] = True
           the_connection = self.get_api().connect(**self.get_config(config))
        else:
           the_connection = self.get_api().connect(**self.get_config(config))
           the_connection.autocommit(True)

        return the_connection**

**Comment by sdispater** [comment]
Are you using  the `mysql-python` package to provide `mysqldb` by any chance?

If that's the case you have to use `mysqlclient` instead which is a maintained fork of `mysql-python` with bugfixes and python 3 support, and it is the one supported by `orator`.

It also have proper support for the `autocommit` keyword: https://github.com/PyMySQL/mysqlclient-python/blob/cba486e0438c2bbad9802667c7a1db0efc591b04/MySQLdb/connections.py#L135

**Comment by crowdmetricivar** [comment]
yeah i am using mysql-python to provide msqldb . tnx for the tip regarding mysqlclient
