### ISSUE TITLE
Typo in docs for model observer methods

### ISSUE THREAD

**Issue by cselmer** [sdispater/orator#149]
On [this page](https://orator-orm.com/docs/0.9/orm.html#model-observers), the synatax for model observer methods is documented as:

```
class UserObserver(object):

    def saving(user):
        # ...

    def saved(user):
        # ...
```

The correct syntax appears to be:

```
class UserObserver(object):

    def saving(self, user):
        # ...

    def saved(self, user):
        # ...
```

If you can point me to a repo where the documentation is stored, I'd be more than happy to submit a PR for this (and a few other) typos I've run across.

**Comment by sdispater** [comment]
Thanks.

The repo for the documentation is here: https://github.com/orator-orm/docs

**Comment by cselmer** [comment]
Resolved with https://github.com/orator-orm/docs/pull/6
