### ISSUE TITLE
[UnsupportedDriver] Driver "psycopg2" is not supported for postgres

### ISSUE THREAD

**Issue by vimox-shah** [sdispater/orator#152]
It is mention on the site that use psycopg2 for postgres sql but it is not working while I run python db.py migrate command. 
app.py

```
from flask import Flask
from flask_orator import Orator
from orator import DatabaseManager

app = Flask(__name__)
app.config['ORATOR_DATABASES'] =  {
    'development': {
        'driver': 'psycopg2',
        'database': 'test'
    }
}
db = Orator(app)
class User(db.Model):


    __fillable__ = ['name', 'email']

    def __repr__(self):
        return '<User %r>' % self.name
```
![screenshot from 2017-03-10 15-21-59](https://cloud.githubusercontent.com/assets/24619300/23790518/68905abe-05a5-11e7-801b-b532d9752b6c.png)

**Comment by vimox-shah** [comment]
hey @sdispater can you please suggest solution for this?

**Comment by sdispater** [comment]
`psycopg2` is the name of the python package you need to install. It's not the driver name. The driver name is `pgsql`.

**Comment by vimox-shah** [comment]
I tried with driver name as postgres and it worked for me . thanks for help.
