### ISSUE TITLE
chunk should use cursors

### ISSUE THREAD

**Issue by tcwalther** [sdispater/orator#158]
The current chunk method uses [`self.for_page`](https://github.com/sdispater/orator/blob/0.9/orator/query/builder.py#L1161), which issues a `SELECT ... LIMIT .. OFFSET ...` query for every single chunk. This is highly inefficient for large tables, and can furthermore lead to race conditions:

- A producer calls `SELECT all rows that aren't processed ORDER BY id OFFSET 0 LIMIT 10`, and sends those row IDs to consumers. The row IDs are 0..9.
- A consumer updates the table as it processes the first row with id 0.
- A producer calls `SELECT all rows that aren't processed ORDER BY id OFFSET 10 LIMIT 10`. The query doesn't count the first row anymore, and as such, the producer skips row 10 and selects rows 11.20.

Instead, Orator should iterate over the result set using a cursor and `fetchmany()`.

**Comment by sdispater** [comment]
While I agree it could be a better implementation, the current architecture prevents it from being trivial to implement.

So, I can't give an ETA for when it will land in Orator.

**Comment by tcwalther** [comment]
Hi @sdispater, thanks for your quick reply, I really appreciate it.

What changes do you think would be necessary to implement this feature? As it currently stands, I would rather advocate on removing the method, as using it can be highly misleading.

**Comment by sdispater** [comment]
Commit 802d0958349050e5a54b763a0c423f8ea47e40c6 should fix the issue.

**Comment by tcwalther** [comment]
Woah. That was fast. I'll test this tomorrow; thanks a lot for this!!

**Comment by sdispater** [comment]
@tcwalther Did it solve the issue?

**Comment by tcwalther** [comment]
Hi @sdispater, this does indeed solve the issue. Thank you very, very much for fixing it!

**Comment by luoxiaohei** [comment]
Hey guys,

I found if use `fetchmany` method  cursor will query all rows from server,  and save rows in memory. 

`chunk` method already can't to avoid consuming RAM, the document will be need update.
