### ISSUE TITLE
Running migrations programmatically

### ISSUE THREAD

**Issue by pandasauce** [sdispater/orator#159]
A fairly common scenario with ActiveRecord due to coupling that it imposes: you need to test something using a database.

In order to do that, I need to run migrations when setting up a test and to revert them when tearing it down, or just to run a ```migrate:refresh``` before every test - doesn't matter which. Currently there is no easy way to do so. I looked into code to see if I could somehow call ```RefreshCommand``` by instantiating that class and passing parameters to it, but it looks like this task would be much more involved than that.

Is there an easy way to achieve this or is the feature just not there?

**Comment by finetuned89** [comment]
I usually do:

    from subprocess import call
    call(["orator", "migrate:rollback", "-n"])
    call(["orator", "migrate", "-n"])

But I agree that it would be nice to have it built in.

**Comment by sdispater** [comment]
I know there is no documented way of executing migration programmatically but you can take a look at the `migrate` and `migrate:rollback` command.

A sample code would be:

```python
from orator.migrations import Migrator, DatabaseMigrationRepository

repository = DatabaseMigrationRepository(db, 'migrations')
migrator = Migrator(repository, db)  # db is the DatabaseManager instance

if not migrator.repository_exists():
    repository.create_repository()

migrator.set_connection('pgsql')  # Needed only if it's not the default database
migrator.run(migrations_path)  ## migrations_path is the directory where you migration files are

# If you want to rollback
migrator.rollback(migrations_path)
```

**Comment by sicksid** [comment]
Hey @sdispater it would be nice to have that way of programmatically running migrations in the documentation, i tried it because im doing a new project setup and i was configuring the test suites, it works very nicely

**Comment by pokono** [comment]
+1

**Comment by josephmancuso** [comment]
here's an example outside of the flow of Orator

https://github.com/MasoniteFramework/core/blob/2.2/masonite/helpers/migrations.py
