### ISSUE TITLE
Collection of a SQlite database query contains Cursors, not Records

### ISSUE THREAD

**Issue by finetuned89** [sdispater/orator#162]
Performing the following on a MySQL table:

    my_users = db.table('users').where('name', 'Steve').get()

returns a `Collection` containing `Record` objects that can be dealt with in a "dict-like" fashion. This also means that we can use `to_json()` or `pop()` or other methods on the `Collection` to deal with the results in a convenient way.

Performing the same operation on a SQLite table, results in a `Collection` object, **but each item in the Collection is a `DictCursor` object** which cannot be serialized or dealt with in an easy way.

Am I using this wrong or should this work the same for MySQL and SQLite?

**Comment by sdispater** [comment]
It should work the same. I will take a look at it.

**Comment by sdispater** [comment]
It should be fixed in commit ac674247dfc3a88bf93ba4d09f5b83dae40ea110 on the `0.9` branch.

The fix will land in the next `0.9.6` release.
