### ISSUE TITLE
 eager load nested relationships better to support multiple levels

### ISSUE THREAD

**Issue by jychen7** [sdispater/orator#168]
currently it supports only one level. 
e.g. `books = Book.with_('author.contacts').get()` will eager load `contacts`

Suppose each `contact` belongs_to a `country`

`books = Book.with_('author.contacts.country').get()` won't eager load `country`

**Comment by jychen7** [comment]
Also if `author` has_many `addresses`, I am not sure how to eager load in current syntax.

maybe we can adopt dictionary like ActiveRecord, e.g.
```
Book.with_(
  {'author': ['contacts', 'addresses']}
).get()

Book.with_(
  {
    'author': [
      {'contacts': 'country'},
      'addresses'
    ]
  }
).get()
```

**Comment by sdispater** [comment]
Thanks for reporting this!

Multiple levels should definitely work. It must me a bug.

Also, you could do:

```python
Book.with_('author.contacts.country', 'author.addresses').get()
```

Anyway, I will investigate the multiple levels issue.

**Comment by sdispater** [comment]
After proper testing `books = Book.with_('author.contacts.country').get()` loads the `country` relation correctly.
