### ISSUE TITLE
v0.9.6 has error when using command

### ISSUE THREAD

**Issue by jychen7** [sdispater/orator#172]
https://github.com/sdispater/orator/blob/ce6c4c3b22a5e034f5c6a6926572887a76c7ed02/orator/commands/application.py#L4
```
from ..version import VERSION
application = Application('Orator', VERSION, complete=True)
```
but version is removed at https://github.com/sdispater/orator/commit/9498167aa98d94138333f213b83e3ee1229b8dfe

**Comment by sdispater** [comment]
Sorry about that. I will definitely release a hotfix by the end of the day.

**Comment by sdispater** [comment]
Version `0.9.7` is out!

**Comment by jychen7** [comment]
appreciate
