### ISSUE TITLE
Running migrations silently 

### ISSUE THREAD

**Issue by finetuned89** [sdispater/orator#174]
I used to be able to run:

    orator migrate -n

Which would run the migrations without prompting. This seems to no longer work in 0.9.7. I have also tried

    echo y | orator migrate

Which also no longer works. The command simply returns:

    Command Cancelled!

Is there a way to run the migrations silently? I use this for automatic deployments and continuous integration.

**Comment by finetuned89** [comment]
Looking at the code for `command.py` and related modules, one way of doing it is to use the `-f` option. I'm not sure what other side-effects that might have:

````
def confirm_to_proceed(self, message=None):
    if message is None:
        message = 'Do you really wish to run this command?: '

    if self.option('force'):
        return True

    confirmed = self.confirm(message)

    if not confirmed:
        self.comment('Command Cancelled!')

         return False

    return True
````

From `migrate_command.py`, I see that it starts with:

    if not self.confirm_to_proceed(
        '<question>Are you sure you want to proceed with the migration?</question> '
    ):
        return


I'm not sure how the `self.confirm_to_proceed` gets set, and if the `-n` option was removed intentionally. Perhaps it is related to the update of Cleo?

**Comment by sdispater** [comment]
Yes, you should use the `-f|--force` option to run migrations without confirmation.

The `-n` option uses the default answers configured for each question. In the case of `migrate` those are set to `False` to avoid running migrations by mistake, thus the addition of the `-f` option
