### ISSUE TITLE
Wrong command in Seed documentation

### ISSUE THREAD

**Issue by canimus** [sdispater/orator#179]
Reference is: [here](https://orator-orm.com/docs/0.9/seeding.html)
The last part of the documentation in the Seed section refers to the command:
```sh
orator migrations:refresh --seed
```

It should be changed to:
```sh
orator migrate:refresh --sed
```

Happy to contribute and change it, but documentation does not have a repo?

**Comment by sdispater** [comment]
The documentation is here: https://github.com/orator-orm/docs :-)

**Comment by cselmer** [comment]
I think I fixed this with the PR that was approved, but it appears the change is only in the master branch, not the 0.9 branch. 

https://github.com/orator-orm/docs/commit/697dbfd5a5515a8b841a6d425f7243f5b787a0c2

**Comment by sdispater** [comment]
Documentation has been updated!
