### ISSUE TITLE
Use two more database in single project

### ISSUE THREAD

**Issue by jarklee** [sdispater/orator#202]
I want to use two mysql database in single project. How should I config orator to deal with that problem.

**Comment by jairojair** [comment]
Hi @jarklee 

You check this section -> https://orator-orm.com/docs/0.9/basic_usage.html what's your question?

**Comment by josephmancuso** [comment]
Closing. Answer is here:
https://orator-orm.com/docs/0.9/basic_usage.html#accessing-connections
