### ISSUE TITLE
Please resolve it or tell me away to resolve it as soon as possible

### ISSUE THREAD

**Issue by ankii9600** [sdispater/orator#210]
![screenshot from 2018-01-11 15-55-13](https://user-images.githubusercontent.com/13003611/34823218-9fb4d43e-f6ef-11e7-9a0d-ae2c088c370a.png)

**Comment by procaff3inator** [comment]
For now using MySQLdb seems like an appropriate workaround.

**Comment by josephmancuso** [comment]
This is a duplicate issue for #218 so I'll close this.
