### ISSUE TITLE
mysql support utf-8 mb4

### ISSUE THREAD

**Issue by GiovanniCardamone** [sdispater/orator#216]
Hello, i need to store some string in `utf-8 mb4` encoding, i used the default method for Schema builder
`table.string('label')`

but when i try to store some date this is the error i got:
`orator.exceptions.query.QueryException: (1366, "Incorrect string value: '\\xF0\\x9F\\x8D\\x90' for column 'label' at row 1")`

the bytes ''\\xF0\\x9F\\x8D\\x90' is the 🍐 charater.

there is a way i can support it?

**Comment by josephmancuso** [comment]
What is your database information?

**Comment by tonyzhangcn** [comment]
I met the same problem but solved by adding "'charset': 'utf8mb4'," to the orator config file and set the mysql table to default encoding of utf8mb4.

**Comment by zardilior** [comment]
@tonyzhangcn  exactly where do we add the charset within the database params?
