### ISSUE TITLE
Losing connections on production

### ISSUE THREAD

**Issue by procaff3inator** [sdispater/orator#218]
Hi, we've been facing issues with orator on prod. After some debugging I found out that the errors raised by pymysql says 'Lost connection' and in the [source](https://github.com/sdispater/orator/blob/586cf6b69f9b69c257b75c7efa0e053b36eece96/orator/connections/connection.py#L348) there's a check for 'Lost Connection' (capital 'C').

This is probably the same issue as #210.

I have also seen a couple of attempts at resolving this issue.
#217 
#199 

It would be nice if one of these pull requests were merged soon since it has been affecting multiple users.

For now using MySQLdb seems like an appropriate workaround.

**Comment by josephmancuso** [comment]
I'll look into this and accept one of the available PR's fixing this issue. Thanks for reporting!

**Comment by josephmancuso** [comment]
Fixed and merged in #217
