### ISSUE TITLE
Add support to Oracle Database

### ISSUE THREAD

**Issue by vitorluis** [sdispater/orator#220]
Hello guys, first of all, thanks for this awesome ORM, its really easy to use!

I would like to know if we can add support to Oracle databases? Is there something which blocks the Oracle implementation?

Thanks

**Comment by josephmancuso** [comment]
All underlining ORM's (including Orator) has what is called a DBAL (database abstraction layer) which is designed to be a middleman between the ORM and the database. Adding support for other databases will entail creating a new DBAL. If you would like to explore the codebase a bit and open an issue about how you will implement this then we can explore this further. I'll add this issue to the roadmap.
