### ISSUE TITLE
How to make custom relation?

### ISSUE THREAD

**Issue by seoyoungjin** [sdispater/orator#224]
I'm migration from rails to orator. I met following relation that doesn't math orator relationships.
<pre>
countries
    id - integer
    name - string

users
    id - integer
    country_id - integer
    name - string

posts
    id - integer
    owner_id - integer
    owner_type - string
------------------------------------------------------
- In country
has_many: users
has_many: posts, :through => users            <--------------- Problem
- In user
has_one: posts :as => owner
</pre>

It looks like 'has_many_through' but with two columns.
I think that I have to make custom relationship. Could you give me a some tip?

**Comment by seoyoungjin** [comment]
Following is my db query.  How can I make this as relation or iinstace's property?
<pre>
clause = JoinClause('user').\
    on('posts.owner_id', '=', 'user.id'). \
    on('posts.owner_type', '=', 'SOME'). \
    where('user.country_id', '=',  3)

db.table('posts').join(clause).get()
</pre>

**Comment by seoyoungjin** [comment]
I made following custom relation. Is there any clean method to define custom relations?
In larabel, I found following link. https://github.com/johnnyfreeman/laravel-custom-relation

<pre>
    @property
    def doodad_funcs(self):
        from orator.query.join_clause import JoinClause
        from . import DoodadFunc
        clause = JoinClause('doodad_func_loot_items').\
                on('doodad_funcs.actual_func_id', '=', 'doodad_func_loot_items.id').\
                on('doodad_funcs.actual_func_type', '=', 'DoodadFuncLootItem')
        return (
            DoodadFunc.join(clause).select('doodad_funcs.*'). \
                    where('doodad_func_loot_items.item_id', '=', self.id).get()
        )
</pre>

**Comment by josephmancuso** [comment]
Not really sure what you're asking here. Maybe you can explain more?

You can just specify another model to return:

```
def doodad_funcs(self):
    from . import DoodadFunc
    return DoodadFunc.posts()
```
