### ISSUE TITLE
distinct() lost after relation decorator

### ISSUE THREAD

**Issue by seoyoungjin** [sdispater/orator#227]
Followings are my model and relation query and corresponding SQL.
With @has_many, DISTINCT is missed in SQL.
<pre>
    @has_many
    def buff_breakers(self):
        from .buff_breaker import BuffBreaker
        return (
            BuffBreaker
                .order_by('id', 'desc')
                .distinct()
        )
</pre>

<pre>
>>> BuffBreaker.order_by('id', 'desc').distinct().find(1)
Executed ('SELECT DISTINCT * FROM "buff_breakers" WHERE "buff_breakers"."id" = ? ORDER BY "id" DESC LIMIT 1', [1]) in 0.29ms
>>> b = Buff.first()
Executed ('SELECT * FROM "buffs" LIMIT 1', []) in 0.5ms
>>> b.buff_breakers
Executed ('SELECT * FROM "buff_breakers" WHERE "buff_breakers"."buff_id" = ? ORDER BY "id" DESC', [1]) in 0.51ms
</pre>

**Comment by seoyoungjin** [comment]
Following patch solves this issue.
```
--- orator/query/builder.py.org	2018-03-22 22:24:13.954975081 +0900
+++ orator/query/builder.py	2018-03-22 22:25:37.514957582 +0900
@@ -1617,6 +1617,7 @@
         self.groups += query.groups
         self.havings += query.havings
         self.orders += query.orders
+        self.distinct_ = query.distinct_
 
         if self.columns:
             self.columns = Collection(self.columns).unique().all()
```

**Comment by josephmancuso** [comment]
How can I reproduce this? I have reproduced the has many relationships but how did you go about viewing the queries it generated?

**Comment by nhaga** [comment]
Distinct() doesn't seem to be working...

class Auction(db.Model):
    @belongs_to_many('auction_bids', 'auction_id', 'instrument_id')
    def instruments(self):
        return Instrument.distinct()
