### ISSUE TITLE
creating schema, if table name is having schema in it

### ISSUE THREAD

**Issue by JahangerGull** [sdispater/orator#236]
Hi

Following code is getting failed as the schema "test" does not exist:

```
        with self.schema.create('test.config') as table:
            table.increments('id')            

```

Is there any other way to define/create the DB schema before running the actual query?

Thanks

**Comment by josephmancuso** [comment]
Are you talking about creating the actual database?

**Comment by JahangerGull** [comment]
Not a DB, just creating a new schema in DB. I don't want the tables to be added to the public schema.

Is there any other way around we can run customer queries in the migrations? something like this in the migration file.

```
    def up(self):
        """
        Run the migrations.
        """
        self.schema.execute("create schema test")
        with self.schema.create('test.config') as table:
```

Thanks

**Comment by josephmancuso** [comment]
ah I see. for Postgres. umm i don't think so honestly but I wouldn't be surprised if there is but it's undocumented. There are a few things that aren't documented well. Let me check codebase

**Comment by JahangerGull** [comment]
Ok, looking into the code, I got following way to create the schema:

`self.db.statement("create schema test")`

Its sufficient for now, and can go ahead.

Thanks for a quick reply.

**Comment by josephmancuso** [comment]
great can you post the whole code snippet so others can follow along?

**Comment by JahangerGull** [comment]
Scenario: To have some custom query in your migration, or creating a DB schema so tables can go within that:


```
from orator.migrations import Migration


class MyShcema(Migration):

    def up(self):
        """
        Run the migrations.
        """
        self.db.statement("create schema if not exists test")
        
        with self.schema.create('test.users') as table:
            table.increments('id')            
            table.timestamps()

            table.string("name")

    def down(self):
        """
        Revert the migrations.
        """
        self.schema.drop('test.users')
        self.db.statement("drop schema test")
```

Thanks
