### ISSUE TITLE
Model building with different databases

### ISSUE THREAD

**Issue by JahangerGull** [sdispater/orator#237]
Hi

I am building an API, and it can communicate with 2 Databases, and for that in my projected inherited my models from different Model. But whats happening is that previous Model configuration gets overwrite with the next one. 

For e.g, this is how I tried to do

```
DB_Model.set_connection_resolver(DatabaseManager({'db': db_config}))    
DW_Model.set_connection_resolver(DatabaseManager({'dw': dw_config}))    

```
Now when I inherit my models from DB_Model and DW_Model only DW_Model settings will be available for moth Models configurations.

Is there any way we can define multiple Model, communicating with different databases?

Thanks

**Comment by josephmancuso** [comment]
You should set multiple configurations into a single config dictionary

```python
config = {
    'default': 'mysql',
    'connection1': {
        'driver': 'mysql',
        'host': 'localhost',
        'database': 'database',
        'user': 'root',
        'password': '',
        'prefix': ''
    },
    'connection2': {
        'driver': 'Postgres',
        'host': 'localhost',
        'database': 'database',
        'user': 'root',
        'password': '',
        'prefix': ''
    },
}
```

and then adjust the connection on your model:

Possibly something like:

```python
class User(Model):
    __connection__ = 'connection2'
```

I believe that is the way to do it

**Comment by josephmancuso** [comment]
refer to this: https://orator-orm.com/docs/0.9/orm.html#defining-a-model and the blue info box under neath one of the code samples

**Comment by JahangerGull** [comment]
Perfect, this is what I was looking for.

Thanks
