### ISSUE TITLE
Auto-Incrementing column that is not a primary key

### ISSUE THREAD

**Issue by rohalla2** [sdispater/orator#239]
I am looking to create a table that has an auto-incrementing integer that is not a primary key:
```python
with self.schema.create('contributors') as table:
      table.timestamp('updated_at').use_current()
      table.string('modified_by')
      table.integer('version_number').unisgned()
      table.string('record_id')
      table.integer('contributor_id', True)
      table.string('first_name')
      table.string('last_name')
      table.string('middle_initial')
      table.string('pseudonym')

      table.primary('record_id')

```

In this example I want `record_id` to be my primary key and `contributor_id` to be auto-incrementing but NOT a primary key. When I run this as a migration using Postgres for my DB I get the following error:
```bash
[QueryException]
multiple primary keys for table "contributors" are not allowed
(SQL: ALTER TABLE "contributors" ADD PRIMARY KEY ("record_id") (None))
```
Removing the `contributor_id` column results in the migration being successfully run.  How can I prevent autoincrement from making itself a key?

**Comment by josephmancuso** [comment]
yeah i'm pretty sure tables are not allowed to have multiple primary keys.

I've never actually used this but does this work?:

```python
table.increments('contributor_id')
```

?

**Comment by josephmancuso** [comment]
is `table.primary()` even a thing? where did you get that from?

**Comment by rohalla2** [comment]
I found `table.primary()` in the docs [here](https://orator-orm.com/docs/0.9/schema_builder.html#adding-indexes)

**Comment by rohalla2** [comment]
Using `table.string('record_id').primary()` produces the same error.

**Comment by josephmancuso** [comment]
i don't think you can have a non primary auto incrementing ID

**Comment by josephmancuso** [comment]
you'd have to maintain it yourself i think

**Comment by josephmancuso** [comment]
I think you'd have to do use the `increment('contributor_id', 1)` method
