### ISSUE TITLE
will orator close db connection automatically after executing one line

### ISSUE THREAD

**Issue by ranit-geek** [sdispater/orator#242]
hi,
I wanted to know is there auto db connection close possible after my db operation is over in orator?

**Comment by josephmancuso** [comment]
Yes orator handles opening and closing of all database connections internally

**Comment by ranit-geek** [comment]
I have given DB config  in
` db = DatabaseManager(config)`

so for example say if I am executing this line:
`results = db.select('select * from users where id = ?', [1])
`
will the db connection get closed after executing this line?

**Comment by josephmancuso** [comment]
Yes. You can view open connections in your database. If it is not disconnecting then open an issue please

**Comment by ranit-geek** [comment]
sure Thanks for the info 👍 -)
