### ISSUE TITLE
AttributeError: 'Car' object has no attribute 'name'

### ISSUE THREAD

**Issue by sreenadh** [sdispater/orator#254]
c = Car()
print c.name

AttributeError: 'Car' object has no attribute 'name'

**Comment by sreenadh** [comment]
@jairojair 
Model "Car" has the following attributes
id, name

What I wanted is,
in Controller
model = Car()

and use the following in Kajiki template
<input type='text' value='${model.name}'/> 

But it is giving the error.

**Comment by josephmancuso** [comment]
you need to do a lookup. A model doesn't have an attribute. Active record style ORMS add attribute after it is fetched from the table (using the table schema.)

You need something like

```python
c = Car.find(<id of row>)
print c.name
```

**Comment by sreenadh** [comment]
Can't we read the schema and create attributes on __init__() @josephmancuso

**Comment by josephmancuso** [comment]
I mean, you COULD but why would you?

what are you expecting `.name` to be? 

```
c = Car()
print c.name
```

how does it know the name of the car? you need to fetch the record first from the database in order to know the name of the car.

what are you trying to do?

**Comment by sreenadh** [comment]
Can we do this?

```
def __getattribute__(self, attr):
        if attr != 'attributes' and hasattr(self, 'attributes'):
            if  attr in self.attributes:
                return self.attributes[attr]
        
        return super(Base, self).__getattribute__(attr)
```

**Comment by sreenadh** [comment]
@josephmancuso  I am trying to create a form using the model. if it is 
model = Car.find(1) 
on update(self, id):

it will fill the text box with the value from the DB.
if it is a new model. empty textbox.

On submission, post data after validation is mapped to attributes of the model and save()

**Comment by josephmancuso** [comment]
you would need to do this for a new record:

```python
c = Car
c.name = 'some-value'
c.engine = 'some-other-value'
c.save()
```

boom. Now you have a new record. For a new record, don't worry about the attributes not being set before hand. Orator will take care of that. The above code will work. For updating do:

```python
c = Car.find(1)
c.name = 'some-value'
c.engine = 'some-other-value'
c.save()
```

**Comment by jairojair** [comment]
@sreenadh the @josephmancuso tips solve your issue?
