### ISSUE TITLE
Add call to action to docs site home page

### ISSUE THREAD

**Issue by florimondmanca** [sdispater/orator#270]
Hi,

The docs site for Orator ORM is, indeed, beautiful.

I'm just thinking it misses a call to action button on the landing page, something like "Get started" or "Read the docs".

Not sure if this is the place to discuss the docs site — I haven't found its repo, but if there's one I'd be happy to transfer the issue over there!

**Comment by josephmancuso** [comment]
It's a little hidden https://github.com/orator-orm/docs :)
