### ISSUE TITLE
first_or_create not returning complete model

### ISSUE THREAD

**Issue by robertmylne** [sdispater/orator#271]
```
       search = Search.first_or_create(
            category_id=category.id,
            location_id=location.id,
            query=category.name,
            location=location.name
        )
       print(search.complete)
```

In the table `search` there is a column `complete` set to `0` as default.

When the `first_or_create` method does a `first` the `complete` field is present. 

When it does a `create` the returned model does not know about the `complete` field from the database. Is there a way to refresh the model so it actually gets the full record it creates in the database?

**Comment by josephmancuso** [comment]
interesting I will look into this. I am trying to learn the Orator codebase so I can officially take it over. This is a good issue to look into

**Comment by josephmancuso** [comment]
after doing more research into this, This is intentional. reason being that this is a small use case to add to the core library and it will add an additional query every time you create a new model. which is not good. In cased like these you have 2 options:

Option 1: If you know the default, specify the default when you create the record:

```python
       search = Search.first_or_create(
            category_id=category.id,
            location_id=location.id,
            query=category.name,
            location=location.name,
            complete=0
        )
       print(search.complete)
```

Option 2:

Create a some refill logic like this:

```
class SomeModel:
    ...
    __refills__ = ['completed']

    def refills(self):
        for refill in self.__refills__:
            if not hasattr(self, refill):
                return self.find(self.id) # Fetches by the recently created ID
        return self
```

You can then use it like this:

```python
       search = Search.first_or_create(
            category_id=category.id,
            location_id=location.id,
            query=category.name,
            location=location.name
        )
       print(search.complete) #== EXCEPTION

       search = Search.first_or_create(
            category_id=category.id,
            location_id=location.id,
            query=category.name,
            location=location.name
        ).refills()
       print(search.complete) #== '1' shows the default value because it ran a "find()"
```
