### ISSUE TITLE
Does orator DatabaseManager supports SSH tunnel?

### ISSUE THREAD

**Issue by tonyzhangcn** [sdispater/orator#276]
Hello,
The database I'm going to connect is behind a jump server, I need to SSH to that jump server first and then connecting to the DB. Want to check whether the latest version of orator DatabaseManager supports that? Or is there any work around to do that? Thanks!

**Comment by josephmancuso** [comment]
Sadly it does not. Possibly this issue may help: https://stackoverflow.com/questions/25495364/laravel-mysql-db-connection-with-ssh

May need to setup a tunnel on your production server to the other database server.

**Comment by tonyzhangcn** [comment]
thank you for the information :)
