### ISSUE TITLE
Is there any support for the like operator?

### ISSUE THREAD

**Issue by zardilior** [sdispater/orator#285]
Is the like = "%word%", mysql operator supported? 
If it is, it is not in the docs

**Comment by tegarimansyah** [comment]
How about using `where_raw("something LIKE 'this%%' ")` ? Yes, I used % twice.

https://orator-orm.com/docs/0.8/query_builder.html#exists-statement

**Comment by rfschubert** [comment]
Yes, you can use `.where("field", "like", "%word%")`
and also works with `not like`

**Comment by zardilior** [comment]
"%word%" works without double %% ? And woudl there be an eloquent equivalent of just writing .like. Can I add an example to the docs with these answers?

**Comment by josephmancuso** [comment]
there is not. You can make one yourself though. Something like:

```
def where_like(self, column, search):
    return self.where(column, 'LIKE', '%{}%'.format(search))
```
