### ISSUE TITLE
to json dict of collections

### ISSUE THREAD

**Issue by zardilior** [sdispater/orator#288]
How to convert to json to a dict of collections? 

```
 {
     "collection1":<collection1>
     "collection2":<collection2>
 }
```

**Comment by josephmancuso** [comment]
collect has a `.serialize()` method:

```python
Model.all().serialize()
```

**Comment by zardilior** [comment]
Worked like a charm!! thanks a lot, could be worth mentioning it in docs for the json convert specific use case

**Comment by josephmancuso** [comment]
which section are you talking about specifically? The list of collect methods are here: https://orator-orm.com/docs/0.9/collections.html#serialize

The specific code snippet above is here: https://orator-orm.com/docs/0.9/orm.html#converting-a-model-to-a-dictionary

**Comment by zardilior** [comment]
Oh! Thanks you are right it indeed is there very specifically, thanks

**Comment by josephmancuso** [comment]
:)
