### ISSUE TITLE
support created_at without updated_at

### ISSUE THREAD

**Issue by tcwalther** [sdispater/orator#29]
I have a use case where I only insert into a table, and thus would like to omit the `updated_at` column. Rails' ActiveRecord supports that, for example. It would be amazing if Orator could do that, too.

**Comment by sdispater** [comment]
It would be a nice addition, indeed. I will see if I can integrate this in the next version of Orator.

For the time being, as a workaround, you can make a subclass of `Model` which overrides two methods: `set_updated_at` and `uses_timestamps` like so:

```python
from orator import Model


class CreatedAtOnlyModel(Model):

    def set_updated_at(self, value):
        pass

    def uses_timestamps(self):
        return False
```

**Comment by sdispater** [comment]
It is now supported.

Check the [updated documentation](https://orator-orm.com/docs/master/orm.html#timestamps)

**Comment by tcwalther** [comment]
Wow, that was fast. Very impressive. Thanks a lot!

**Comment by sdispater** [comment]
:-) Be aware however, that it's only the develop branch for now.

It will be officially integrated in the future 0.8 version.
