### ISSUE TITLE
where_raw method not work

### ISSUE THREAD

**Issue by paulyim** [sdispater/orator#300]
`rows = Dictionary.where_raw('order_num > ? and ref_times = 0', [3]).get()`

raise QueryException:

`orator.exceptions.query.QueryException: not all arguments converted during string formatting (SQL: SELECT * FROM `sys_dictionary` WHERE order_num > ? AND ref_times = 0 ([3]))`

**Comment by zardilior** [comment]
It is because you are passing an array instead of the number, array notation only works for in and such. Try this way:
rows = Dictionary.where_raw('order_num > ? and ref_times = 0', 3).get()
