### ISSUE TITLE
first_or_create to include a second parameter for values to create the object if the search fails

### ISSUE THREAD

**Issue by bencarter78** [sdispater/orator#301]
Hello

First off, thanks for creating a great project here. Having come from Laravel, it certainly makes getting into python ORMs much more accessible.

I was looking at the first_or_create method and noticed (unlike Laravel) it doesn't have a second parameter for creating the object if the search for the record returns empty handed.

Before starting a pull request, do you think it be a good idea to look at implementing this.

Something like

```
user = User.first_or_create(username='test.mctest', values={'name': 'Test McTest', 'age': 100})
```

Thanks again for your work!

**Comment by josephmancuso** [comment]
Yes you can do that:

```python
User.first_or_create(username='Joe', name='Test McTest', age=100})
```
