### ISSUE TITLE
ORM only creates a model through save method

### ISSUE THREAD

**Issue by bencarter78** [sdispater/orator#302]
Hello

I was hoping someone could explain to me why the `create` method isn't creating a record in the database but if I instantiate the model then `save` it then it will persist in the database.

when using the create method I get the following error.

`TypeError: __init__() got an unexpected keyword argument 'postcode'`

```python
# Not working
location = Location.create(postcode="TS1 3ST")

# Working
location = Location()
location.postcode = "TS1 3ST"
location.save()
```

What am I doing wrong?

Thanks

**Comment by FlashChaser** [comment]
Hey I was having the same issue but I found this in the documentation.

**Comment by FlashChaser** [comment]
Hey I was having the same issue but found this in the documentation.

> You can also use the create method to save a model in a single line, but you will need to specify either the __fillable__ or __guarded__ property on the model since all models are protected against mass-assignment by default.

To use the example in the documentation.
```
# Create a new user in the database
user = User.create(first_name='John')
```

You must make sure the model has the __fillable__ property defined for 'name'.

```
class User(Model):

    __fillable__ = ['first_name', 'last_name', 'email']
```

**Comment by josephmancuso** [comment]
@bencarter78 yes @FlashChaser is correct. That should solve the issue. Orator protects against mass assignment by default so you'll need to explicitly define which columns should be mass assigned using the `__fillable__` property.

Assigning properties to the class and saving does not count as mass assigning and so it will create.
