### ISSUE TITLE
Setting up .env migration and ORM

### ISSUE THREAD

**Issue by oscarmorrison** [sdispater/orator#314]
Related to: #243 

Maybe I am missing something here, but normally with other frameworks I can just have a `.env` file that I can read my db creds from like so:

```
HOST=localhost
DATABASE=databasename
USER=user
PASS=pass
```

Then I can use different creds in different environments (local, staging, prod etc). 

I want to be able to use these for both migrations and models. I cannot work out how to do it. If I setup a `orator.py` and read them in like so:

```
from dotenv import load_dotenv
import os
load_dotenv()

DATABASES = {
        'postgres': {
                'driver': 'postgres',
                'host': os.getenv('HOST'),
                'database': os.getenv('DATABASE'),
                'user': os.getenv('USER'),
                'password': os.getenv('PASSWORD'),
                'prefix': ''
            }
        }
```

then I can't get the model to work like in issue #243 

Thanks

**Comment by kentaro0919** [comment]
Hi @ oscarmorrison
In https://github.com/MasoniteFramework use .env file as you with. You may have a look to the code.

**Comment by oscarmorrison** [comment]
Hi @kentaro0919 my issue isn't that I don't know how to use an env file, its that if you use env in collaboration with the `orator.yml` for migrations you get the issue described here #243

**Comment by josephmancuso** [comment]
I would use either or. 

Use a .env file and a python file to read the environment variables into your settings. You can also build a custom wrapper around switching between local, prod and dev

**Comment by oscarmorrison** [comment]
@josephmancuso please font close this. this is a bug. 
Should be able to use an .env file for both orator and the migration. Or a shared `orator.yml` file

**Comment by josephmancuso** [comment]
You can use a `.env` file for any python file.  The top of your file should look something more like:

```
from dotenv import load_dotenv
from pathlib import Path
load_dotenv(str(Path('.') / '.env'))

import os
DATABASES = {
        'postgres': {
                'driver': 'postgres',
                'host': os.getenv('HOST'),
                'database': os.getenv('DATABASE'),
                'user': os.getenv('USER'),
                'password': os.getenv('PASSWORD'),
                'prefix': ''
            }
        }
```
