### ISSUE TITLE
first_or_new returns soft deleted records.

### ISSUE THREAD

**Issue by pokono** [sdispater/orator#317]
With this code and **SQLite** database:
```python
printer = Printer.first_or_new(identifier=printer_profile["id"])
printer.name = printer_profile["name"]
printer.model = printer_profile["model"]
printer.save()
printer.delete()
```

Expected result: Every time this code run a new record should be created and deleted.

Actual result: Row is created once and deleted. After `first_or_new` keep finding the same row. (same as it was called `with_trashed()`.)

![Screen Shot 2019-07-28 at 5 51 53 AM](https://user-images.githubusercontent.com/358137/62005079-d054a980-b0fb-11e9-8858-6fd32f7e4009.png)

**Migration**
```python
from orator.migrations import Migration
class CreatePrintersTable(Migration):

	def up(self):
		"""
		Run the migrations.
		"""
		with self.schema.create("printers") as table:
			table.increments("id")
			table.string("identifier", 255).unique()
			table.string("name", 255)
			table.string("model", 255)
			table.timestamps()
			table.soft_deletes()

	def down(self):
		"""
		Revert the migrations.
		"""
		self.schema.drop("printers")
```

**Model**
```python
from orator import Model, SoftDeletes
class Printer(Model, SoftDeletes):
	__table__ = "printers"
	__primary_key__ = "id"
	__dates__ = ['deleted_at']
	# __fillable__ = ["identifier", "name", "model"]
	__guarded__ = ["id"]
```

**Comment by josephmancuso** [comment]
This looks to be by design https://github.com/sdispater/orator/blob/bd90bf198ee897751848f9a92e49d18e60a74136/tests/orm/mixins/test_soft_deletes_integration.py#L141

**Comment by pokono** [comment]
@josephmancuso maybe it is by design, but why would this be the correct behaviour? I'm confused. Would you care to elaborate?

**Comment by josephmancuso** [comment]
@pokono not really sure to be honest 🤔 . Would have to ask @sdispater
