### ISSUE TITLE
Model raises an error when trying to save on a table without id column

### ISSUE THREAD

**Issue by angel93ayora** [sdispater/orator#321]
orator 0.9.8
pymysql 0.9.3

i've started to use orator so it's maybe a common mistake

this got solved by adding an id column at db :/
this is only happening when updating an existing row

```
p = Person.first()
p.name = 'foo'
p.save()
```

```
Traceback (most recent call last):
  File "models/Person.py", line 37, in <module>
    p.save()
  File "......\orator\orm\model.py", line 1525, in save
    saved = self._perform_update(query, options)
  File "......\orator\orm\model.py", line 1570, in _perform_update
    self._set_keys_for_save_query(query).update(dirty)
  File "......\orator\orm\model.py", line 1673, in _set_keys_for_save_query
    query.where(self.get_key_name(), self._get_key_for_save_query())
  File "......\orator\orm\model.py", line 1684, in _get_key_for_save_query
    return self._attributes[self.get_key_name()]
KeyError: 'id'
```

**Comment by josephmancuso** [comment]
what is the primary key on the table?

**Comment by josephmancuso** [comment]
oh sorry I missed this line

> this got solved by adding an id column at db :/

you are saying now updating existing records don't work.

**Comment by angel93ayora** [comment]
> oh sorry I missed this line
> 
> > this got solved by adding an id column at db :/
> 
> you are saying now updating existing records don't work. Is that right?

sorry for my english

i was saying that i was unable to update a row that does not have a 'id' column

searching again in the docs i've found that i'll have to set ```__primary_key__``` property to the column name i'm using as identifier

although i was able to insert rows without any complain, on a table without any 'id' column

**Comment by josephmancuso** [comment]
Yes each table needs a primary key which you can set via the `__primary_key__ `. You can rename it whatever you want but it should be on the table.
