### ISSUE TITLE
Default argument value is mutable

### ISSUE THREAD

**Issue by Polyipnus** [sdispater/orator#332]
File: orator/utils/url.py
`
def translate_connect_args(self, names=[], **kw):
`

as function translate\_connect\_args defined  in line 134, has a potential problem, which IDEs will complain with  `Default argument value is mutable`.

**Comment by mandarvaze** [comment]
1. Comment says `names` is Deprecated.
2. `translate_connect_args` itself [does not seem to be used](https://github.com/sdispater/orator/search?q=translate_connect_args&unscoped_q=translate_connect_args) anywhere. 

I wonder if the function itself can be removed all together.

I also noticed that comments in this file (`orator/utils/url.py`) reference SQLAlchemy. I wonder why ?

**Comment by Polyipnus** [comment]
> 1. Comment says `names` is Deprecated.
> 2. `translate_connect_args` itself [does not seem to be used](https://github.com/sdispater/orator/search?q=translate_connect_args&unscoped_q=translate_connect_args) anywhere.
> 
> I wonder if the function itself can be removed all together.
> 
> I also noticed that comments in this file (`orator/utils/url.py`) reference SQLAlchemy. I wonder why ?

I will close this issue, thanks
