### ISSUE TITLE
Eager loading has_many

### ISSUE THREAD

**Issue by camilstaps** [sdispater/orator#34]
Is there a way to do eager loading on a has_many relationship?

When I define a relationship, say in class User

    @has_many
    def articles(self):
        return Article

And query `User.with_('articles')`, N+1 queries are executed. What I would expect is a query like the following:

    SELECT * FROM user INNER JOIN article ON article.user_id = user.id

And Orator grouping the articles by user and returning User objects that have lists of Article objects. Is something like that currently possible?

**Comment by sdispater** [comment]
Eager loading is already possible for has_many relationships, but Orator uses 2 queries instead of using a join query:

```sql
SELECT * FROM users;
SELECT * FROM articles WHERE user_id IN (1, 2, 3, 4, 5, ...);
```

Therefore, you should not see N+1 queries being executed.
Can you tell me exactly the queries you see when you do `User.with_('articles').get()`?

**Comment by camilstaps** [comment]
Apologies, I was at fault. The model and all was fine, but then I used the relationship as a function instead of a property, i.e.:

    for user in User.with_('articles').get().all():
        user.articles().get()

instead of

    for user in User.with_('articles').get().all():
        user.articles

Thanks though, and apologies.
