### ISSUE TITLE
Exception: The helper "dialog" is not defined

### ISSUE THREAD

**Issue by sebastialonso** [sdispater/orator#35]
I'm trying flask-orator and performing the examples in their documentation.
I'm following **exactly** the same instructions of the official tutorial.

When I run the migrations, this happens

![screenshot from 2016-01-27 10 46 22](https://cloud.githubusercontent.com/assets/3493453/12615245/470538be-c4e3-11e5-9e45-6cbd0c926cc9.png)

How did I screw it up? I haven't even defined "dialog" :/

**Comment by sdispater** [comment]
This is partly my fault.

The latest stable version of flask-orator has not been updated to be compatible with the latest version of [cleo](https://github.com/sdispater/cleo).

To fix this, you have two options: replace the 0.4.0 version of cleo by the 0.3.0 for the time being or install flask-orator from the develop branch.

**Comment by sebastialonso** [comment]
Thank you very much for the quick answer. I downgraded cleo for the moment, and I was permitted to continue.

However new undocumented issues appeared

![screenshot from 2016-01-27 12 07 20](https://cloud.githubusercontent.com/assets/3493453/12617470/9c8e6822-c4ee-11e5-8d10-fcdf499c81c2.png)
 and then after I manually wrote a route

![screenshot from 2016-01-27 12 08 21](https://cloud.githubusercontent.com/assets/3493453/12617525/d50a3104-c4ee-11e5-800e-3e3b94bc90cf.png)

But according to the tutorial it was enough with this
~~~
app.config['ORATOR_DATABASES'] = {
  'development': {
    'driver': 'sqlite',
    'database': 'database.db'
   }
}
~~~
in the main file.
What's going on here?

**Comment by sdispater** [comment]
The `--database` options must reference the name of the database you want to use. So here it should be `development` since it's the name you gave to your sqlite database configuration.

**Comment by sebastialonso** [comment]
Thanks! That worked great. I'll write a snippet later for anyone in the same situation.
