### ISSUE TITLE
ColumnDoesNotExist but not actually being referenced

### ISSUE THREAD

**Issue by ninjrdevelop** [sdispater/orator#391]
Hi guys, have a strange issue I'm hoping for some assistance on.

I have a migration: https://gist.github.com/ninjrdevelop/dd5f2715eeef30aca3308042880729a3

When I run it, I get the error:
```
[ColumnDoesNotExist]
  Column "permission_id" does not exist on table "users".
```

migrate -vvv: https://gist.github.com/ninjrdevelop/6bb795742e1f736ff38360a3c89faa8a
migrate --pretend: https://gist.github.com/ninjrdevelop/b1915ac62ae66f2f3d17052b3e04d864

Image of table structure attached.

Any thoughts? There's no reference to `permission_id` anywhere in this project.
![vivaldi_jdRDBd1nMR](https://user-images.githubusercontent.com/72955871/110041008-84beb300-7da8-11eb-8027-e48485eabe15.png)

**Comment by alfonsocv12** [comment]
You just have one migration or have multiple ?

**Comment by ninjrdevelop** [comment]
I have quite a few migrations, as the app has expanded over time. The migration in question was the only one running at the time, as everything else had been sorted previously. None of these have 'permission_id' in them.
![pycharm64_PItWHzjGBW](https://user-images.githubusercontent.com/72955871/112555964-16f92a80-8e2e-11eb-96dc-8c7ea5b2eaa8.png)

**Comment by alfonsocv12** [comment]
Can you run the migrate:status command and take a screenshot of the response ?

**Comment by ninjrdevelop** [comment]
![pycharm64_Kw6v6oW5L5](https://user-images.githubusercontent.com/72955871/112556557-58d6a080-8e2f-11eb-9738-fbfa32e5957f.png)

**Comment by ninjrdevelop** [comment]
Wierd thing is that if I go manually add a 'permission_id' field to the 'users' table, this migration runs perfectly......

**Comment by alfonsocv12** [comment]
Okay i believe the problem is with the db.py file so try using the orator cli alone, I have this configuration for the migrations most of the time.

![Screen Shot 2021-03-25 at 16 39 55](https://user-images.githubusercontent.com/31135704/112557066-c7145800-8d88-11eb-90ac-45f791c4de67.png)

with this file arrangement on top, the command is like this

`orator migrate -c orator_config.py`

the orator_config.py has this in it

```
from env import os

DATABASES = {
    'mysql': {
        'driver': 'mysql',
        'host': os.environ.get('host'),
        'database': os.environ.get('database'),
        'user': os.environ.get('user'),
        'password': os.environ.get('password'),
        'port': os.environ.get('port'),
        'prefix': os.environ.get('prefix'),
    }
}
```

**Comment by ninjrdevelop** [comment]
Sadly no luck.
![pycharm64_aUhgZ347xK](https://user-images.githubusercontent.com/72955871/112560723-a60b4000-8e38-11eb-82f2-731513028c2a.png)

**Comment by josephmancuso** [comment]
Could the issue be related to the fact that you have an orator.py file? This is going to conflict anytime you try to use orator because of python import hierarchy. Try changing the name of that orator.py file to something else

**Comment by ninjrdevelop** [comment]
Touché, didn't think of that. It's now `orator_config.py`, and still the same result as my last image.

**Comment by alfonsocv12** [comment]
@ninjrdevelop Do you have permission_id anywhere on the repository ?

**Comment by ninjrdevelop** [comment]
Nope. 

Just used Find in Folder in Sublime Text and got: 
Searching 4887 files for "permission_id"
0 matches

**Comment by alfonsocv12** [comment]
Jajajaja we're working with a severe case of [Magic (programing)](https://en.wikipedia.org/wiki/Magic_(programming)), I'm out of ideas, but pretty interested to know how you will fix this.

**Comment by ninjrdevelop** [comment]
Haha, yeah that's what I figured. 
I had to keep going, so I just bypassed the issue by actually adding a permission_id field to the user table so it wouldn't complain any longer.
Thanks for the help @alfonsocv12
