### ISSUE TITLE
Can't import model inside seeder

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator#41]
Hello,

I'm trying to seed a database using the command: 
```orator db:seed --seeder=animal_seeder --config=conf.py```

But it can't import model inside the seeder. I was trying to use model factories without any luck. I'm always getting **[ImportError]  No module named xxx** when I try to import the model inside the seeder.

Here is my model:

```python
# ./models/animal.py
from orator import Model

class Animal(Model):
    pass
```

... and my seeder:

```python
# ./seeds/animal_seeder.py
from orator.seeds import Seeder
from models.animal import Animal # [ImportError]  No module named models.animal
# from models import * - [ImportError]  No module named models

class AnimalSeeder(Seeder):
# ...
```

Am I doing something wrong, or is it a real issue?

Thanks.

**Comment by joaobarbosa** [comment]
I've solved the **ImportError** adding my project path to the $PYTHONPATH (export PYTHONPATH=...) and now, the seeder can import the model using ```from models.animal import Animal```.

But now, I'm getting this error: **[AttributeError] 'NoneType' object has no attribute 'connection'**, with the traceback below.

It seems that the *__connection__* property in the Model is None. I've already checked my database conf, and migrations are running fine using the same conf.

Traceback:

```
Exception trace:
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/cleo/application.py in run() at line 88
   status_code = self.do_run(input_, output_)
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/cleo/application.py in do_run() at line 147
   status_code = command.run(input_, output_)
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/cleo/commands/command.py in run() at line 90
   return super(Command, self).run(i, o)
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/cleo/commands/base_command.py in run() at line 148
   status_code = self.execute(input_, output_)
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/commands/command.py in execute() at line 39
   return self.handle()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/commands/seeds/seed_command.py in handle() at line 36
   self._get_seeder().run()
 /home/joaobarbosa/python-projects/web2py/applications/pag/seeds/pag_vei_veiculo_seeder.py in run() at line 15
   self.factory(Veiculo, 1).create()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/factory_builder.py in create() at line 51
   results = self.make(**attributes)
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/factory_builder.py in make() at line 77
   return self._make_instance(**attributes)
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/factory_builder.py in _make_instance() at line 98
   instance = self._klass()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/model.py in __init__() at line 121
   self._boot_if_not_booted()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/model.py in _boot_if_not_booted() at line 148
   klass._boot()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/model.py in _boot() at line 167
   cls._boot_columns()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/model.py in _boot_columns() at line 171
   connection = cls.resolve_connection()
 /home/joaobarbosa/.virtualenvs/pag/local/lib/python2.7/site-packages/orator/orm/model.py in resolve_connection() at line 2759
   return cls.__resolver.connection(connection)
```

**Comment by sdispater** [comment]
I will look into it.

Thanks for the complete feedback :smiley:

**Comment by joaobarbosa** [comment]
@sdispater I've solved it adding my project's root folder to the PYTHONPATH enviroment variable and adding a instance of DatabaseManager to the model (as you say in the docs). I guess this issue is closed.

The main point, I think, is that the docs should mention about adding the project's directories (or at least the models' folder) to the path before trying to use the cli. Maybe it's just lack of experience of mine, I'd like to hear your opinion about it. :)

**Comment by sdispater** [comment]
I will probably update the docs to make it more straightforward.

Thanks for bringing this up :-)

**Comment by tkensiski** [comment]
@sdispater would be nice to get those docs updated... This is not straight forward and I just spent a bit of time looking for an answer with very little results other than this.
