### ISSUE TITLE
About the documentation

### ISSUE THREAD

**Issue by erikstorm** [sdispater/orator#42]
Hey, thanks for great ORM!

I'm currently involved in making a medium size app, and we would be glad to help with the documentation and try to improve and report inconsistencies if we find any.

I noticed the docs folder is gitignored, are you currently improving them or is there another reason they are ignored?

The docs are also hosted on both readthedocs and on the orator-orm.com, which one are you currently prioritizing?

Here is an example I found in the Seeding section;

`orator seeds:make `

which should apparently be

`orator seed:make`

**Comment by sdispater** [comment]
The documentation is in its own repository here : https://github.com/orator-orm/docs

**Comment by erikstorm** [comment]
Thanks for the quick reply, closing the issue.
