### ISSUE TITLE
.unsigned() raises TypeError when running migrations

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator#47]
I was trying to create a foreing key, following the example written in the docs ([https://orator-orm.com/docs/0.8/schema_builder.html#foreign-keys](https://orator-orm.com/docs/0.8/schema_builder.html#foreign-keys)), but when running the migration itself, it's raising a ```TypeError``` exception, with the following message: ```'bool' object is not callable```.

As far as I could investigate, trying to understand how ```.nullable()``` or ```.unique()``` works, I found out that the exception is raised when a Fluent instance's (```table.integer('field_name').unsigned()```) ```__getattr__``` method runs, ```self.get(item, lambda: Dynamic(None, item, self))``` (fluent.py, line 78) returns ```False```. For example, when it runs with ```.nullable```, the same method returns ```None```, because this attribute is not set by default.

When creating an integer or similar field, the attribute ```unsigned``` is set to ```False``` by default, unless you use ```.set_unsigned(True)``` or ```table.unsigned_integer(...)```.

Here is my migration:

```
with self.schema.create('pag_pag_pagamento') as table:
      table.increments('id')
      table.string('name', 255)
      table.integer('status').unsigned()
      table.timestamps()
      table.soft_deletes()
```

**Comment by sdispater** [comment]
I can reproduce the problem. I will look into it.
