### ISSUE TITLE
Migration ValuError exception

### ISSUE THREAD

**Issue by tantita** [sdispater/orator#53]
```
orator make:migration create_users
```
  [ValueError]
  Invalid format string

That is the error I get when I try to create a new migration (on windows and python3.5)

**Comment by sdispater** [comment]
Yes. It's a problem that has been fixed in the `develop` branch, so you can try using this branch for the time being. Otherwise, I will release the `0.8.1` version in the coming week with several fixes, including this one.

**Comment by sdispater** [comment]
Fixed in the latest 0.8.1 version.
