### ISSUE TITLE
AttributeError when trying to use ORM

### ISSUE THREAD

**Issue by nicholastulach** [sdispater/orator#58]
I receive the following error when trying to run the ORM documentation samples

`AttributeError: 'Connection' object has no attribute '_server_version'`

Below is the code i am using with a database `testdb` which has a table `users` with columns for `id` and `name`.

```
from orator import DatabaseManager

config = {
    'mysql': {
        'driver': 'mysql',
        'host': 'localhost',
        'database': 'testdb',
        'user': 'root',
        'password': '',
        'prefix': ''
    }
}

db = DatabaseManager(config)
user = db.table('user').where('name', 'John').first()
print(user['name'])

from orator import Model

Model.set_connection_resolver(db)

class User(Model):
    pass

user = User.find(1)
print(user.name)
```

**Comment by sdispater** [comment]
I has been fixed on the `develop` branch.

See #39 

I will release a new version or Orator this week with this fix included.

**Comment by nicholastulach** [comment]
so current work-around for mysql users is to use mysqlclient instead of pymysql?

**Comment by sdispater** [comment]
You can also install orator from the `develop` branch.
