### ISSUE TITLE
QueryException: not all arguments converted during string formatting

### ISSUE THREAD

**Issue by jefurry** [sdispater/orator#61]
from orator import DatabaseManager
config = {'mysql': {'driver': 'mysql', 'host': 'localhost', 'database': 'jumu', 'user': 'root', 'password': '123456', 'prefix': '', 'port': 3306}}
db = DatabaseManager(config)
results = db.select('select * from admin_user where id = ?', [1])

**QueryException: not all arguments converted during string formatting (SQL: select * from admin_user where id = ? ([1]))**

**Comment by sdispater** [comment]
Yes. It is a known issue with how dbapi packages work in Python.

Each package can use one of many ways to represent parameter binding (sqlite uses the `qmark` (`?`) syntax but mysql and postgres packages uses the `%s` syntax). That's the reason why you encounter this error.

I will make a change this week on the `develop` branch to allow the qmark syntax for every package. This change will be integrated in the next major version (`0.9`).

For now, you query should be:

```python
results = db.select('select * from admin_user where id = %s', [1])
```

**Comment by jefurry** [comment]
thanks, this is a great job.
