### ISSUE TITLE
Fix "Renaming Columns" section in docs

### ISSUE THREAD

**Issue by joaobarbosa** [sdispater/orator#62]
Hi @sdispater,

In the example of how to [rename columns](https://orator-orm.com/docs/0.8/schema_builder.html#renaming-columns), you pointed out the wrong method. Instead of

```python
with schema.table('users') as table:
    table.rename('from', 'to')
```

It should be:

```python
with schema.table('users') as table:
    table.rename_column('from', 'to')
```

Thanks.

**Comment by sdispater** [comment]
Thanks for reporting this.

You can report errors and typo in docs to the official repository : https://github.com/orator-orm/docs

**Comment by joaobarbosa** [comment]
Thanks @sdispater! You've been doing a great job, btw :smile:
