### ISSUE TITLE
Not parsing -n or --no-interaction

### ISSUE THREAD

**Issue by giovanni-liboni** [sdispater/orator#65]
Hi, @sdispater 
i'm running orator (version 0.8.1/OSX) and my migration file is:
```
from orator.migrations import Migration
class CreateUsersTable(Migration):
    def up(self):
        """
        Run the migrations.
        """
    	with self.schema.create('users') as table:
    		table.big_increments('id')
    		table.timestamps()
    		table.string('username', 50)
    		table.string('password', 50)

    def down(self):
        """
        Revert the migrations.
        """
    	self.schema.drop('users')
```
When i launch 
``orator migrate -c databases.py ``
works but when i reset database and launch it again with ``-n`` flag, orator doesn't execute any migration and the database is empty.
It's the correct way to specify no-interaction?

Thanks.

**Comment by sdispater** [comment]
The `-n` flag will use the default value for confirmation. So, since currently it is (wrongfully) set at false by default, it will not run the migrations.

I will fix it.

**Comment by sdispater** [comment]
Commit 5bdf770fcf9d72b61f74692d133bfb8066bdec48 should fix the problem.

Can you try the `0.8` branch and tell me if it works?
