### ISSUE TITLE
Running migrate with --no-interaction does nothing

### ISSUE THREAD

**Issue by darvid** [sdispater/orator#67]
I'm trying to add migrate commands to a Makefile but unfortunately it looks like no-interactive doesn't work with any of the migrate commands.

**Comment by sdispater** [comment]
Yes, it has been reported in #65 

The `-n` option uses the default response for questions which has been wrongfully set to `False`. It will be fixed in the `0.8.2` version

**Comment by sdispater** [comment]
Commit 5bdf770fcf9d72b61f74692d133bfb8066bdec48 should fix the problem.

Can you try the `0.8` branch and tell me if it works?
