### ISSUE TITLE
Method typo error: ._new_picot_statement_for_id

### ISSUE THREAD

**Issue by tantita** [sdispater/orator#68]
In https://github.com/sdispater/orator/blob/0.8/orator/orm/relations/belongs_to_many.py#L634
change 
```
updated = self._new_picot_statement_for_id(id).update(attributes)
```
to
```
updated = self.new_pivot_statement_for_id(id).update(attributes)
```

**Comment by tantita** [comment]
No comment?

**Comment by sdispater** [comment]
Sorry, I did not mark it as closed but it's been fixed in commit 37949d08e25f12cbe7678582b32d3dd65898723b on the `0.8` branch.

**Comment by tantita** [comment]
Ok

**Comment by tantita** [comment]
Hi, Kindly compare these 2 lines:
https://github.com/sdispater/orator/blob/0.8/orator/orm/relations/belongs_to_many.py#L634
updated = self._new_pivot_statement_for_id(id).update(attributes)
and
https://github.com/sdispater/orator/blob/0.8/orator/orm/relations/belongs_to_many.py#L789
 def new_pivot_statement_for_id(self, id):

The method is defined w/o an underscore, and called with an underscore prefix, hence you get the following error when you try to update an existing pivot

EXCEPTION IN (/.../controllers.py, LINE 64 "r.foods().update_existing_pivot(food_id, {data['field']: data['data']})"): <type 'exceptions.AttributeError'> _new_pivot_statement_for_id

The solution should be to change _new_pivot_statement_for_id on line 634 to new_pivot_statement_for_id

**Comment by sdispater** [comment]
Thanks for investigating it.

I just pushed a fix (26666bd4a0d268d3f3cbdb144dec8521c01db6d3) on the `develop` branch. The fix will be included in the next `0.9` major version .

**Comment by tantita** [comment]
You welcome sir

**Comment by tantita** [comment]
Hi, please try and push this fix to the current main branch as this is a trivial issue.
Thanks
