### ISSUE TITLE
Recursive belongs_to / has_many relationship

### ISSUE THREAD

**Issue by tdpsk** [sdispater/orator#70]
Hi all,

I have been struggeling lately to find a solution for one of my problems: I have a model "Category", which can have a parent. So one category might belong to another category as a child.

If I now use the normal belongs_to and has_many decorators provided by Orator, I receive Python errors because class loading is caught in a recursion loop. Is there a supported way to create such a relationship (a model belonging to itself)?

See an example of what I tried below:

```python
class Category(Model):
     __table__ = 'categories'
    
    @has_many('parent', 'id')
    def children(self):
        return Category
     
    @belongs_to('parent')
    def parent(self):
        return Category
```

**Comment by sdispater** [comment]
You have a problem in your model. This is what it should look like

```python
class Category(Model):

    @has_many('parent_id')
    def children(self):
        return Category

    @belongs_to
    def parent(self):
        return Category
```
or, if you want to be more verbose:

```python
class Category(Model):

    __table__ = 'categories'

    @has_many('parent_id', 'id')
    def children(self):
        return Category

    @belongs_to('parent_id')
    def parent(self):
        return Category
```

**Comment by tdpsk** [comment]
Thanks, but wouldn't that mean the foreign-key field in my database has to be called "parent_id"? Is there a specific reason the field can't be called "parent"?

**Comment by sdispater** [comment]
`parent` is the name of your `belongs_to` relation. Therefore the foreign key must have another name for Orator to properly handle the relation.
