### ISSUE TITLE
Invalid default value for 'updated_at'

### ISSUE THREAD

**Issue by 12789** [sdispater/orator#74]
I got a migration issue.

> orator migrate
>
> Are you sure you want to proceed with the migration? y
>
>  [QueryException]    
>                                                           
>   (1067, "Invalid default value for 'updated_at'") (SQL: CREATE TABLE `categories` (`id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY, `created_at` TIMESTAMP NOT NULL, `updated_at` TIMESTAMP NOT NULL) (None))   

                 
**MySQL: 5.7.12**

**migration file:**

```
from orator.migrations import Migration


class CreateCategoriesTable(Migration):

    def up(self):
        """
        Run the migrations.
        """
        with self.schema.create('categories') as table:
            table.increments('id')
            table.timestamps()

    def down(self):
        """
        Revert the migrations.
        """
        self.schema.drop('categories')
```

**Comment by sdispater** [comment]
It's not in the documentation yet, but you can use the `use_current=True` keyword for the `timestamps()` method to set the default value to the current time.

**Comment by felipevolpone** [comment]
I get the same error. So, maybe it's a good idea the default value of  use_current be True.
Something like:
```python
def timestamp(self, use_current=True):
``` 
I think this is easier and really intuitive. What do you think?

**Comment by sdispater** [comment]
Yes, it seems like a good idea to make it the default value.

The change will be trageted for the next `0.9` release.

**Comment by joaobarbosa** [comment]
When this issue happened with me, I dig into it and found out that MySQL 5.7 makes **NO_ZERO_DATE**  mode enabled by default. (http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html).

When Orator indicates a not null timestamp field without a explicit default value, the database will try to use '0000-00-00 00:00' - conflicting with **NO_ZERO_DATE** mode. I solved it by disabling the SQL mode (better explained on this article: https://www.sitepoint.com/quick-tip-how-to-permanently-change-sql-mode-in-mysql/).

**Comment by sdispater** [comment]
Thanks for the clarifications.

I think that, to avoid the hassle of digging into the MySQL configuration file, it's better to make the `use_current` value to default to `True`. It's more intuitive in my opinion.

**Comment by joaobarbosa** [comment]
Sure, I agree. :)
