### ISSUE TITLE
charmap UnicodeEncodeErorr on windows

### ISSUE THREAD

**Issue by revictus** [sdispater/orator#75]
When you run a migration on windows it throws the following error (migration still successfully runs): 

  [UnicodeEncodeError]
  'charmap' codec can't encode character '\u2713' in position 5: character maps to undefined

Character u2713 is the checkmark that is present in the self._note in the migrator.py file

**Comment by sdispater** [comment]
Which Python version are you using?

**Comment by sdispater** [comment]
The checkmark has been removed for now. Everything should work properly in the latest `0.8.2` version.
