### ISSUE TITLE
Add a Makefile to the project to ease contributions

### ISSUE THREAD

**Issue by scorphus** [sdispater/orator#78]
Hello, Sébastien.

I see `.gitignore` has a `Makefile` entry in it, right at the bottom. This hints at an existing `Makefile`. If that's the case, would you like to add it to the project? I think it may ease contributions. Along with some docs, but that's for another pull request...

If that's not the case, I can create a `Makefile`, for which I already have a kinda-working draft.

Thanks!

**Comment by sdispater** [comment]
There was a Makefile, but it was mainly to build the sphinx documentation. However, it is now in its own repository: https://github.com/orator-orm/docs

But I agree that it would ease contributions. I will look into it.

**Comment by scorphus** [comment]
Cool! Let me propose one, I'll open a pull request as soon as I get the chance.
