### ISSUE TITLE
Timezone setting

### ISSUE THREAD

**Issue by tantita** [sdispater/orator#83]
Hi, I noticed you used arrow library from datetime management. Is there a way to modify the Timezone as it defaults to UTC. Thanks

**Comment by sdispater** [comment]
The default timestamp is determine by the `fresh_timestamp()` method of the models, so you could overwrite it like this:

```python
class User(Model):

    def fresh_timestamp(self):
        return arrow.now().naive
```

**Comment by tantita** [comment]
Pls how I do simply convert every timestamp column (created_at and updated_at) to UTC+1 time zone when accessing then. I want to leave them stored as UTC in d database

**Comment by sdispater** [comment]
The easiest way would be to use an [accessor](https://orator-orm.com/docs/master/orm.html#accessors-mutators), like so:

```python
import arrow
from orator.orm import accessor

class User(Model):

    @accessor
    def created_at(self):
        return arrow.get(self._attributes['created_at']).to('Europe/Paris')
```

**Comment by tantita** [comment]
When I did this, I was getting a JSON serialization error, as the result of the model was to be coverted to a dict using the to_dict() method and passed to jsonify thus:
```
return(jsonify({"orders": user.orders().order_by("created_at","DESC").get().to_dict()}))
```
The problem with the solution u provided was that the accessor returned an object of type Arrow, while I think the serializer was expecting a datetime object.

Anyways, I found a hack around it by creating an accessor in the model thus:
```
 @accessor
    def created_at(self):        
        dt = arrow.get(self.get_raw_attribute('created_at')).to('+01:00')
        return datetime(dt.year, dt.month, dt.day, dt.hour, dt.minute, dt.second).isoformat()
```

This should suffice for now till I get a better solution

**Comment by sdispater** [comment]
Yes, the example I gave you actually raises an error. That's a problem in how the accessors work for date attributes.

Basically, once an attribute has been marked as mutated (either with the `accesor` or the `mutator` decorator) it will not be properly serialized.

I will see how to fix it.

**Comment by sdispater** [comment]
The serialization error should be fixed on the `develop` branch.

**Comment by mouday** [comment]
i use like this:

```python
 def fresh_timestamp(self):
        return pendulum.now()
```
