### ISSUE TITLE
Attribute Error :  'module' object has no attribute 'table'

### ISSUE THREAD

**Issue by Karthick6038** [sdispater/orator#88]

**Comment by Karthick6038** [comment]
I am trying to use the query instead of model. But it throws the following error,

Query : db.table('users').select('id').get()

AttributeError: 'module' object has no attribute 'table'

**Comment by sdispater** [comment]
Strange. What's the exact code that triggers the error (how is the DatabaseManager initialized?)

**Comment by Karthick6038** [comment]
Sorry, issue on my side. I rectified.
