### ISSUE TITLE
How to group_by year or month in orator?

### ISSUE THREAD

**Issue by JunyuMu** [sdispater/orator#92]
this is my table:
```python
 with schema.create("post") as table:
        table.increments("id")
        table.string("title", 256)
        table.text("content")
        table.timestamps()
```

I want post query group by year. like:
```sql
query = db.table("post").order_by('created_at', 'desc').group_by('year').get()
```

**Comment by sdispater** [comment]
Sorry for not getting back to you sooner.

Did you close this because you found a solution?

For now, there is no easy and builtin way to order by a unit of a timestamp. Maybe by using a raw group by for your specific backend.
