### ISSUE TITLE
Just a doubt about test with arrow library

### ISSUE THREAD

**Issue by Marlysson** [sdispater/orator#93]
In a test case you used the Arrow Library .. Why not the Pendulum? Since handle better datetimes .. as shown in documentation them .. Or was it a matter of choice..

**Comment by sdispater** [comment]
When I started Orator, Pendulum did not exist so I used the more popular library at the time. But now I have updated the code (see f9090931c38c0c25d66ffaf4264458190c4ef936) to use Pendulum in the next major version (0.9).

**Comment by Marlysson** [comment]
Ok , what date will be launched?

**Comment by sdispater** [comment]
I don't have a fixed release date yet. Shouldn't be long now. Probably in early september.

**Comment by Marlysson** [comment]
" - The arrow library wasn's working for me then I create a better. " kkk ( About Pendulum )

Very cool these library.
