### ISSUE TITLE
Belongs_to not being loaded in accessor

### ISSUE THREAD

**Issue by tdpsk** [sdispater/orator#94]
I have a children / parent relationship which I modelled using has_many / belongs_to. The code I use is below:

```python
class StoreModel(db.Model):
    @has_many('parent_id', 'id')
    def children(self):  # pragma: no cover
        return StoreModel

    @belongs_to('id', 'parent_id')
    def parent(self):  # pragma: no cover
        return StoreModel


    @accessor
    def url(self):
        self.load('parent')

        if not self.deeplink:
            if self.parent:
                    return parent.url
            return 'no parent!'

       return self.deeplink
```

As you can see, url should return the parent deeplink if no deeplink is set for this model. However in my tests, I always receive a "no parent!", although the parent_id is set correctly. 

The following manual loading code works as expected and return the parent deeplink correctly:

```python
    @accessor
    def url(self):
        if not self.deeplink:
            if self.parent_id:
                parent = StoreModel.find_or_fail(self.parent_id)
                return parent.url
            return 'no parent!'
        return self.deeplink
```

So it seems that the parent is not being loaded although the parent_id is set correctly. Am I wrong to use belongs_to / has_many in this context?

**Comment by sdispater** [comment]
I think you have have the parameters in `belongs_to` backwards, it should be:

```python
@belongs_to('parent_id', 'id):
def parent(self):
    return StoreModel
```

**Comment by sdispater** [comment]
@tdpsk Did it solve your problem?

**Comment by tdpsk** [comment]
Yes, my fault, thanks for the help!
