### ISSUE TITLE
What are the major new things I need to change in my code if I want to use the develop branch

### ISSUE THREAD

**Issue by tantita** [sdispater/orator#95]
Ok, so i updated my code to use the develop branch, since that's where all the bug fixes go to,and i noticed that the to_dict() method of the model has been removed(I was getting a fatal error in my code for this method), so I checked the last commits on the develop branch and changed all to_dict() reference in my code to serialize()

My question now is: Is there any other major change that's incompatible with the develop branch that I need to change in my code just like I did for the to_dict() method?

**Comment by sdispater** [comment]
Not much as there are not a lot of breaking changes:

- All `to_dict()` methods have been replaced by `serialize()`
- The ORM no longer returns `Arrow` instances but [Pendulum](https://github.com/sdispater/pendulum) instances.
- Collections are no longer bundled in Orator. Orator now depends on [backpack](https://github.com/sdispater/backpack) for collections. So be sure to have it installed.

And that's pretty much it. The rest is fixes and improvements.

For the complete list of changes: https://github.com/sdispater/orator/compare/develop
